home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('story1', views.story1, name='story1'),
    path('mail', views.mail, name='mail'),
    path('tambah_matkul', views.tambah_matkul, name='tambah_matkul'),
    path('list_matkul', views.list_matkul, name='list_matkul'),
    path('hapus_matkul', views.hapus_matkul, name='hapus_matkul')
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('aktivitas/', include('kegiatan.urls')),
    path('accord/', include('accord.urls')),
    path('books/', include('books.urls')),
    path('user/', include('users.urls'))
]

home/models.py
from django.db import models

# Create your models here.

class MataKuliah(models.Model):
    nama = models.CharField(max_length=30)
    dosen = models.CharField(max_length=30)
    sks = models.CharField(max_length=30)
    semester = models.CharField(max_length=30)
    ruangan = models.CharField(max_length=30)
    deskripsi = models.TextField()

    def __str__(self):
        return self.nama

home/forms.py
from django import forms
from .models import MataKuliah
#from .models import MataKuliah

class FormBiasa(forms.Form):
    nama_matkul = forms.CharField()
    dosen_pengajar = forms.CharField()
    sks = forms.CharField()
    semester = forms.CharField()
    ruangan = forms.CharField()
    deskripsi = forms.CharField(widget=forms.Textarea)

class FormMatkul(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = (
            'nama', 'dosen', 'sks', 'semester',
            'ruangan', 'deskripsi'
        )

class FormHapus(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = ('nama',)

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import FormBiasa, FormMatkul, FormHapus
from .models import MataKuliah
# Create your views here.

response = {}

def index(request):
    return render(request, 'home/index.html')

def story1(request):
    return render(request, 'home/story1.html')

def mail(request):
    return render(request, 'home/mail.html')

def tambah_matkul(request):
    if request.method == 'POST':
        form = FormMatkul(request.POST)
        if form.is_valid():
            form.save()
            print(form)
            
    form = FormMatkul()
    return render(request, 'home/matkul.html', {'form' : form})

def list_matkul(request):
    list_matkul = MataKuliah.objects.all()
    response['list_matkul'] = list_matkul
    return render(request, 'home/list_matkul.html', response)

def hapus_matkul(request):
    
    if request.method == 'POST':
        form = FormHapus(request.POST)
        if form.is_valid():
            nama_del = request.POST['nama']
            for matkul in MataKuliah.objects.all():
                if matkul.nama == nama_del:
                    item = MataKuliah.objects.get(nama = nama_del)
                    item.delete()
                    break
                
    form = FormHapus()
    return render(request, 'home/hapus_matkul.html', {'form':form})

home/templates/home/hapus_matkul.html
{% extends 'home/base.html' %}
{% load static %}
    {% block meta %}
    <title>Mau Hapus Matkul?</title>
    <link rel="stylesheet" href="{% static 'home/style3.css' %}">
    <style>
        .hapus-container{
            margin-left: 28%;
        }

        .hapus-container .btn-container{
            margin-left: 15%;
            margin-top: 3%;
        }
        .hapus-container .halo{
            margin-left: 15%;
            margin-top: 5%;

        }
        h4{
            margin-left: 15%;
        }
    </style>
    {% endblock meta %}
    {% block content %}
    <div class="hapus-container">
    <div class="halo" style= "display: flex;">
        <h3 style="color: white; font-weight: 400;">Halo, </h3>
        <h3 style="color: lightskyblue; margin-left: 1%;">Pram</h3>
    </div>
    <h4 style="font-weight: 300; color: white;">Mau menghapus matkul?</h4>
    <div class="btn-container">
        <a href="{% url 'home:index' %}" class="link-home"><button class="btn-light">Home</button></a>
        <a class="link-list" href="{% url 'home:list_matkul' %}"><button class="btn-info">Lihat Matkul</button></a>
        <a class="link-tambah" href="{% url 'home:tambah_matkul' %}"><button class="btn-primary">Tambah Matkul</button></a>
    </div>
    <form method="post" style="color: white; width: 50%; margin-left: 5%; display: flex; flex-direction: column;">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn-success" style="margin-top: 5%;">Hapus</button>
    </form>
    </div>
    
    {% endblock content %}

home/templates/home/index.html
{% extends 'base.html' %}
{% load static %}
    {% block meta %}
    <title>Hey, It's Pram</title>
    <link rel="stylesheet" href="{% static 'home/style3.css' %}" />
    {% endblock meta %}

    {% block content %}
    <div class="section" id="about" style="min-height: 657px">
      <div class="bio">
        <h3 class="big">HEY, I'M PRAM</h2>
        <h3 class="big">COMPUTER SCIENCE STUDENT</h2>
        <h3 class="big">AT UNIVERSITY OF INDONESIA</h2>
        <h3 class="medium"><span>I LIKE MOVIES, BASKETBALL, AND KPOP</span></h2>
      </div>
      <div class="profpic">
        <img src="{% static 'home/ini-pram.jpg' %}" alt="profile" />
      </div>
    </div>
    <div class="section" id="skill">
      <div class="desc">
        <p>
          <b>
            An easygoing person who likes to learn new<br />things especially
            if it's interesting. I try to<br />always give off positive vibes
            but honestly i just<br />accepted who i really am and things that
            God<br />gave me.
          </b>
        </p>
      </div>
      <h2>Skill</h2>
      <div class="skill-img">
          <img src="{% static 'home/python.png' %}" alt="python">
          <img src="{% static 'home/java.png' %}" alt="java">
          <img src="{% static 'home/premiere.svg' %}" alt="adobepremiere">
          <img src="{% static 'home/basketball.svg' %}" alt="basketball">
      </div>
    </div>
    <div class="section" id="experience">
      <h2>Experience</h2>
      <div class="exp-container">
          <div class="exp">
              <p class="pos"><b>Vice Person in Charge of Campaign</b></p>
              <p class="comp">Pemira Fasilkom UI 2020</p>
          </div>
          <div class="vl"></div>
          <div class="exp">
              <p class="pos"><b>Student Mentor</b></p>
              <p class="comp">PMB Fasilkom 2020</p>
          </div>
          <div class="vl"></div>
          <div class="exp">
              <p class="pos"><b>Staff of Advocation and Student Welfare</b></p>
              <p class="comp">BEM Fasilkom UI 2020</p>
          </div>
          <div class="vl"></div>
          <div class="exp">
              <p class="pos"><b>Staff of Bazaar</b></p>
              <p class="comp">PERAK Fasilkom 2020</p>
          </div>
      </div>
    </div>
    <div class="section" id="gallery" style="min-height: 657px">
      <h2>Gallery</h2>
      <div class="container">
          <div class="img-container">
              <img src="{% static 'home/Sabpel2.jpg' %}" alt="sabpel">
              <p>Sabtu Pelangi<br>21 September 2019</p>
          </div>
          <div class="img-container">
              <img src="{% static 'home/Setara2.jpg' %}" alt="setara">
              <p>SETARA<br>6 Oktober 2019</p>
          </div>
          <div class="img-container">
              <img src="{% static 'home/Reformasi1.jpeg' %}" alt="reformasi">
              <p>Reformasi Dikorupsi<br>24 September 2019</p>
          </div>
      </div>
    </div>
  </div>
  <div class="section" id="contact">
    <h2>Contact Me</h2>
    <hr>
    <div class="contact-links">
        <a href="https://www.instagram.com/naufalpraam/"><img src="{% static 'home/instagram.png' %}" alt="instagram"></a>
        <a href="https://www.linkedin.com/in/naufal-pramudya-yusuf-793872193/"><img src="{% static 'home/linkedin.png' %}" alt="linkedin"></a>
        <a href="https://twitter.com/thisispramie"><img src="{% static 'home/twitter.png' %}" alt="twitter"></a>
        <a id="email" href="{% url 'home:mail' %}"><img src="{% static 'home/email.png' %}" alt="email"></a>
    </div>
    <p>Copyright © 2020  Naufal Pramudya Yusuf | naufal.pramudya11@gmail.com</p>
  </div>
  {% endblock content %}

home/templates/home/list_matkul.html
{% extends 'base.html' %}
{% load static %}
    {% block meta %}
    <title>List Mata Kuliah</title>
    <link rel="stylesheet" href="{% static 'home/style3.css' %}">
    <style>
        
        .matkul-container{
            margin: 10%;
            margin-top: 5%;
            margin-left: 10%;
            
        }
        .matkul-container .btn-container{
            margin-left: 35%;
            margin-top: 3%;
        }
        .matkul-container .table{
            margin-top: 2%;
        }

        .matkul-container .halo, h4{
            margin-left: 35%;
        }
        
    </style>
    {% endblock meta %}
    {% block content %}
    <div class="matkul-container">
    <div class="halo" style= "display: flex;">
        <h3 style="color: white; font-weight: 400;">Halo, </h3>
        <h3 style="color: lightskyblue; margin-left: 1%;">Pram</h3>
    </div>
    <h4 style="font-weight: 300; color: white;">Yuk dilihat daftar matkulmu!</h4>
    <div class="btn-container">
    <a href="{% url 'home:index' %}" class="link-home"><button class="btn-light">Home</button></a>
    <a class="link-tambah" href="{% url 'home:tambah_matkul' %}"><button class="btn-primary">Tambah Matkul</button></a>
    <a class="link-hapus" href="{% url 'home:hapus_matkul' %}"><button class="btn-danger">Hapus Matkul</button></a>
    </div>
    {% if list_matkul %}
    <table class="table">
        <thead style="text-align: center;">
            <th scope="col">Nama Matkul</th>
            <th scope="col">Dosen Pengajar</th>
            <th scope="col">Deskripsi</th>
            <th scope="col">Semester</th>
            <th scope="col">Ruang</th>
            <th scope="col">SKS</th>
        </thead>
        {% for matkul in list_matkul %}
        <tr>
            <th>{{matkul.nama}}</th>
            <th>{{matkul.dosen}}</th>
            <th>{{matkul.deskripsi}}</th>
            <th>{{matkul.semester}}</th>
            <th>{{matkul.ruangan}}</th>
            <th>{{matkul.sks}}</th>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
    </div>
    {% endblock content %}

home/templates/home/mail.html
{% extends 'base.html' %}
{% load static %}
    {% block meta %}
    <title>Send Mail to Pram!</title>
    <link rel="stylesheet" href="{% static 'home/style3.css' %}" />
    {% endblock meta %}
    {% block content %}
    <div class="full" style="text-align: center;">
      <div class="full-item">
      <div class="contact-title">
        <h1>Hello friends</h1>
        <h3>Send Pram some advice so you can help him make a better website!</h3>
      </div>
      <div class="contact-form">
        <form id="contact-form" method="POST" action="">
          <input
            type="text"
            name="name"
            class="form-control"
            placeholder="Your Name"
            required
          />
          <br />
          <input
            type="email"
            name="email"
            class="form-control"
            placeholder="Your Email"
            required
          />
          <br />
          <textarea
            name="message"
            class="form-control"
            placeholder="Message"
            row="4"
            required
          ></textarea
          ><br />
          <input type="submit" class="form-control submit" value="SEND MESSAGE" />
        </form>
      </div>
      </div>
    </div>
  {% endblock content %}

home/templates/home/matkul.html
{% extends 'base.html' %}
{% load static %}
    {% block meta %}
    <title>Hey, Tambahkan Mata Kuliah?</title>
    <link rel="stylesheet" href="{% static 'home/style3.css' %}" />
    {% endblock meta %}
    {% block content %}
    <div class="container" style="margin: 20px; width: 50%; margin-left: 5%;">
    <div style= "display: flex;">
        <h3 style="color: white; font-weight: 400;">Halo, </h3>
        <h3 style="color: lightskyblue; margin-left: 1%;">Pram</h3>
    </div>
    <h4 style="font-weight: 300; color: white;">Mau tambahkan mata kuliah?</h4>
    <br>
    <div class="btn-container">
    <a href="{% url 'home:index' %}" class="link-home"><button class="btn-light">Home</button></a>
    <a class="link-list" href="{% url 'home:list_matkul' %}"><button class="btn-info">Lihat Matkul</button></a>
    </div>
    <form method="post" style="display: flex; flex-direction: column; color: white;">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn-success">Save</button>
    </form>
    </div>
    {% endblock content%}

home/templates/home/story1.html
{% extends 'base.html' %}
{% load static %}

    {% block meta %}
    <title>Story 1 Pram</title>
    <link rel="stylesheet" href="{% static 'home/style1.css' %}" />
    {% endblock meta %}
    {% block content %}
      <div class="main-content">
        <div class="avatar">
          <img src="{% static 'home/ini-pram.jpg' %}"" alt="Foto Pram"/>
        </div>
        <div class="about">
          <h2>Naufal Pramudya Yusuf</h2>
          <h4>Computer Science 2019</h4>
          <h4>University of Indonesia</h4>
          <p>
            I'm an easygoing person who likes to learn new things especially if
            it's interesting. I try to always give off positive vibes but
            honestly i just accepted who i really am and things that God gave
            me.
          </p>
        </div>

        <div class="contact">
          <a href="https://www.instagram.com/naufalpraam/">
            <img src="{% static 'home/instagram.svg' %}" alt="instagram" />
          </a>
          <a
            href="https://www.linkedin.com/in/naufal-pramudya-yusuf-793872193/"
          >
            <img src="{% static 'home/linkedin.svg' %}" alt="linkedin" />
          </a>
          <a href="https://twitter.com/thisispramie">
            <img src="{% static 'home/twitter.svg' %}" alt="twitter" />
          </a>
        </div>
      </div>
      <div class="list">
        <ul class="hobi">
          <li><b>Hobbies</b></li>
          <li>Movies</li>
          <li>Basketball</li>
          <li>Kpop</li>
        </ul>

        <table class="edu" border="1">
          <tr>
            <td><b>Education</b></td>
            <td><b>Year</b></td>
          </tr>
          <tr>
            <td>University of Indonesia</td>
            <td>2019-present</td>
          </tr>
          <tr>
            <td>SMAN 70 Jakarta</td>
            <td>2016-2019</td>
          </tr>
          <tr>
            <td>SMPN 19 Jakarta</td>
            <td>2013-2016</td>
          </tr>
        </table>
      </div>
      <br />
      <div class="credit">
        Icons made by
        <a href="https://www.flaticon.com/authors/freepik" title="Freepik"
          >Freepik</a
        >
        from
        <a href="https://www.flaticon.com/" title="Flaticon">
          www.flaticon.com</a
        >
      </div>
  {% endblock content %}