home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('story1', views.story1, name='story1'),
    path('mail', views.mail, name='mail'),
    path('tambah_matkul', views.tambah_matkul, name='tambah_matkul'),
    path('list_matkul', views.list_matkul, name='list_matkul'),
    path('hapus_matkul', views.hapus_matkul, name='hapus_matkul')
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('aktivitas/', include('kegiatan.urls')),
    path('accord/', include('accord.urls')),
    path('books/', include('books.urls')),
    path('user/', include('users.urls'))
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.user, name='user'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('bio/', views.bio, name='bio')
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    firstname = models.TextField(max_length=100, blank=True)
    lastname = models.TextField(max_length=100, blank=True)
    bio = models.TextField(max_length=500, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

users/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

# Create your views here.


def user(request):
    return render(request, 'users/user.html')


def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if not username or not password:
            messages.error(
                request, "Please enter username / password correctly")
            return HttpResponseRedirect('/user/signup/')
        if User.objects.filter(username__iexact=username).exists():
            messages.error(request, "Username taken")
            return HttpResponseRedirect('/user/signup/')
        else:
            user = User.objects.create_user(
                username=username, password=password)
            user.save()
            messages.success(request, 'Account Successfully Created!')
            return HttpResponseRedirect('/user/login/')
    else:
        return render(request, 'users/signup.html')


def log_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if not username or not password:
            messages.error(
                request, "Please enter username / password correctly")
            return HttpResponseRedirect('/user/login/')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/user/')
        else:
            messages.error(
                request, "Wrong credentials (Wrong Username / Password)")
            return HttpResponseRedirect('/user/login/')
    else:
        return render(request, 'users/login.html')


def log_out(request):
    logout(request)
    messages.success(request, 'Log out Success')
    return render(request, 'users/login.html')


def bio(request):
    if request.method == 'POST':
        user = User.objects.get(pk=request.POST['id'])
        user.username = request.POST['username']
        user.profile.firstname = request.POST['firstname']
        user.profile.lastname = request.POST['lastname']
        user.profile.bio = request.POST['bio']
        user.save()
        return HttpResponseRedirect('/user/')

    return render(request, 'users/bio.html')

users/templates/users/bio.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Edit your Bio?</title>
<link rel="stylesheet" href="{% static 'home/style3.css' %}" />
<style>
    .container{
        color: #ffffff;
    }
</style>
{% endblock meta %}
{% block content %}
<div class="container">
    {% for message in messages %}
    <script>
      alert("{{ message }}")
    </script>
  {% endfor %}

  {% if user.is_authenticated %}
  <h1>Update Profile</h1>
  <br>
  <h2> Whats up, {{ user.username }}! </h2>

  <form action="" method="POST">
      {% csrf_token %}
      <label for="#username">Username</label>
      <input id="username" name="username" class="form-control" value="{{ user.username }}" type="text" required>
      <label for="#firstname">First Name</label>
      <input id="firstname" name="firstname" class="form-control" type="text" value="{{ user.profile.firstname }}">
      <label for="#lastname">Last Name</label>
      <input id="lastname" name="lastname" class="form-control" type="text" value="{{ user.profile.lastname }}">
      <label for="#bio">Bio</label>
      <input id="bio" name="bio" class="form-control" type="text" value="{{ user.profile.bio }}">
      <br>
      <input type="hidden" name="id" value="{{ user.id }}">
      <input type="submit" value="Update Profile" class="btn btn-primary" id="update">
    </form>
    {% else %}
        <h2> You haven't logged in yet </h2>
    <p> Log in to update your profile </p>
    <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
    {% endif %}
</div>
{% endblock content %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Login</title>
<link rel="stylesheet" href="{% static 'home/style3.css' %}" />
<style>
    .container{
        color: #ffffff;
    }
</style>
{% endblock meta %}
{% block content %}
<div class="container">
        
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <script>
            alert("{{ message }}")
        </script>
        {% endfor %}
    </ul>
    {% endif %}

    {% if user.is_authenticated %}
        <h1>Selamat Datang {{ user.username }} !!</h1>
            <a class="btn btn-primary" href="{% url 'users:logout' %}">Logout</a>
    {% else %}
    <h1>Log In</h1>
    <p>Don't have an account? You can create it  <a href="{% url 'users:signup' %}">here</a></p>
    <form  action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
            <label for="#username">Username</label>
            <input id="username" name="username" class="form-control" type="text">
            <label for="#password">Password</label>
            <input id="password" name="password" class="form-control" type="password">
            <br>
            <input id="sub-login" class="btn btn-primary" type="submit" value="Log In">
        </form>
    {% endif %}
</div>
{% endblock content %}

users/templates/users/signup.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Sign Up</title>
<link rel="stylesheet" href="{% static 'home/style3.css' %}" />
<style>
    .container{
        color: #ffffff;
    }
</style>
{% endblock meta %}
{% block content %}
<div class="container">
        
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <script>
            alert("{{ message }}")
        </script>
        {% endfor %}
    </ul>
    {% endif %}

    {% if user.is_authenticated %}
        <h1>Logged as {{ user.username }}</h1>
            <a class="btn btn-primary" href="{% url 'users:logout' %}">Logout</a>
            {% else %}
                <h1>Sign Up</h1>
                <p>Have an account? You can log in <a href="{% url 'users:login' %}">here</a></p>
                <form  action="{% url 'users:signup' %}" method="POST">
                    {% csrf_token %}
                    <label for="#username">Username</label>
                    <input id="username" name="username" class="form-control" type="text">
                    <label for="#password">Password</label>
                    <input id="password" name="password" class="form-control" type="password">
                    <br>
                    <input id="sub-signup" class="btn btn-primary" type="submit" value="Sign me up!">
                </form>
    {% endif %}
</div>
{% endblock content %}

users/templates/users/user.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>User Page</title>
<link rel="stylesheet" href="{% static 'home/style3.css' %}" />
<style>
    .container{
        color: #ffffff;
    }
</style>
{% endblock meta %}
{% block content %}
<div style="margin-top: 1em;" class="container">

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <script>
            alert("{{ message }}")
        </script>
        {% endfor %}
    </ul>
    {% endif %}

    {% if user.is_authenticated %}
        <h3>Selamat Datang {{ user.username }} !!</h3>
        <div>First Name: {{ user.profile.firstname }}</div>
        <div>Last Name: {{ user.profile.lastname }}</div>
        <div>Bio :  {{ user.profile.bio }} </div>
        <br>
        <br>    
        <a id='sub-update' class="btn btn-primary" href="{% url 'users:bio' %}">Update Profile</a>
        <a id='sub-logout' class="btn btn-primary" href="{% url 'users:logout' %}">Logout</a>
      {% else %}
        <h1>You are not logged in.</h1>
        <br>
        <h3>Do you have an account?</h3>
        <a id='login' class="btn btn-success" href="{% url 'users:login' %}">Log in</a>
        <a id='signup' class="btn btn-outline-success" href="{% url 'users:signup' %}">Sign up</a>
      {% endif %}

</div>
{% endblock content %}