accord/urls.py
from django.urls import path

from . import views

app_name = 'accord'

urlpatterns = [
    path('', views.accordion, name='accordion'),
]

books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('', views.books, name='books'),
    path('fetch/', views.fetch, name='fetch')
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('story1', views.story1, name='story1'),
    path('mail', views.mail, name='mail'),
    path('tambah_matkul', views.tambah_matkul, name='tambah_matkul'),
    path('list_matkul', views.list_matkul, name='list_matkul'),
    path('hapus_matkul', views.hapus_matkul, name='hapus_matkul')
]

kegiatan/urls.py
from django.urls import path

from . import views

app_name = 'kegiatan'

urlpatterns = [
    path('', views.list_aktivitas, name='list_aktivitas'),
    path('tambah_peserta/<int:id>', views.tambah_peserta, name='tambah_peserta'),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('aktivitas/', include('kegiatan.urls')),
    path('accord/', include('accord.urls')),
    path('books/', include('books.urls')),
    path('user/', include('users.urls'))
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.user, name='user'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('bio/', views.bio, name='bio')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> 
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300;400;500&family=Oswald:wght@400;500&family=Poppins&family=Roboto:ital,wght@0,400;1,300&family=Sansita+Swashed:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'home/nav-style.css' %}" />
    {% block meta %}
    {% endblock meta %}
</head>
<body>
  <div class="fullpage">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: lightskyblue;">
          <a class="navbar-brand" href="{% url 'home:index' %}">Nap</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav ml-auto">
              <a class="nav-link active" href="{% url 'home:index' %}#about">Home <span class="sr-only">(current)</span></a>
              <a class="nav-link" href="{% url 'home:index' %}#experience">Experience</a>
              <a class="nav-link" href="{% url 'home:index' %}#gallery">Gallery</a>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Projects
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'home:story1' %}">Story 1</a>
                  <a class="dropdown-item" href="{% url 'home:list_matkul' %}">Mata Kuliah</a>
                  <a class="dropdown-item" href="{% url 'kegiatan:list_aktivitas' %}">Aktivitas</a>
                  <a class="dropdown-item" href="{% url 'accord:accordion' %}">Accordion</a>
                  <a class="dropdown-item" href="{% url 'books:books' %}">Books?</a>
                  <a class="dropdown-item" href="{% url 'users:user' %}">User</a>
                </div>
              </li>
              <a class="nav-link" href="#contact">Contact</a>
            </div>
          </div>
      </nav>
    </header>
    {% block content %}
    {% endblock content %}
  </div>
</body>
</html>