home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('story1', views.story1, name='story1'),
    path('mail', views.mail, name='mail'),
    path('tambah_matkul', views.tambah_matkul, name='tambah_matkul'),
    path('list_matkul', views.list_matkul, name='list_matkul'),
    path('hapus_matkul', views.hapus_matkul, name='hapus_matkul')
]

kegiatan/urls.py
from django.urls import path

from . import views

app_name = 'kegiatan'

urlpatterns = [
    path('', views.list_aktivitas, name='list_aktivitas'),
    path('tambah_peserta/<int:id>', views.tambah_peserta, name='tambah_peserta'),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('aktivitas/', include('kegiatan.urls')),
    path('accord/', include('accord.urls')),
    path('books/', include('books.urls')),
    path('user/', include('users.urls'))
]

kegiatan/models.py
from django.db import models

# Create your models here.

class Aktivitas(models.Model):
    aktivitas = models.CharField(max_length=30)

class Peserta(models.Model):
    peserta = models.CharField(max_length=30)
    kegiatan = models.ForeignKey(Aktivitas, on_delete=models.CASCADE)

kegiatan/forms.py
from django import forms
from .models import Aktivitas, Peserta


class FormAktivitas(forms.ModelForm):
    aktivitas = forms.CharField(max_length=50, widget=forms.TextInput(
        attrs={
            'class' : 'form-control mx-auto'
        }, 
    ))
    class Meta:
        model = Aktivitas
        fields = ('aktivitas',)


class FormPeserta(forms.ModelForm):
    peserta = forms.CharField(max_length=50, widget=forms.TextInput(
        attrs={
            'class' : 'form-control mx-auto'
        }, 
    ))
    class Meta:
        model = Peserta
        fields = ('peserta',)
    

kegiatan/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from .models import Aktivitas, Peserta
from .forms import FormAktivitas, FormPeserta
# Create your views here.

def list_aktivitas(request):
    list_aktivitas = Aktivitas.objects.all()
    list_peserta = Peserta.objects.all()
    form = FormAktivitas()
    form_peserta = FormPeserta()
    if request.method== "POST":
        form = FormAktivitas(request.POST)
        if form.is_valid():
            form.save()
            form = FormAktivitas()
    else:
        FormAktivitas()
    
    pass_arg =  {
        'form':form,
        'list_ak':list_aktivitas,
        'list_pes':list_peserta,
        'Ada':True
    }
    return render(request, 'kegiatan/list_aktivitas.html',context=pass_arg)

def tambah_peserta(request, id):
    list_peserta={}
    kegiatan = get_object_or_404(Aktivitas, pk=id)
    if request.method == 'POST':
       form_peserta = FormPeserta(request.POST)
       if form_peserta.is_valid():
            list_peserta = form_peserta.save(commit=False)
            list_peserta.kegiatan = kegiatan
            list_peserta.save()
            return redirect('/aktivitas/')
    else:
        form_peserta = FormPeserta()
        
    pass_args = {
        'peserta':list_peserta,
        'form':form_peserta
    }
    return render(request, 'kegiatan/tambah_peserta.html', context=pass_args)

kegiatan/templates/kegiatan/list_aktivitas.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Aktivitas</title>
<link rel="stylesheet" href="{% static 'home/style3.css' %}">
<style>
    h3, h4{
        color: white;
    }
    .akt-container{
        margin-left: 2%;
        margin-top: 2%;
    }
</style>
{% endblock meta %}
{% block content %}
<div class="akt-container">
    <div class="row" style="display: flex;">
        <h3 style="font-weight: 400;">Halo, </h3>
        <h3 style="color: lightskyblue;">Pram</h3>
    </div>
    <h4 class="row" style="font-weight: 300;">Jalani harimu dengan senyum!</h4>
    <h4 class="row">Tambahkan aktivitas baru?</h4>
    <div class="row">
    <form method="post" style="display: flex;flex-direction: column; width: fit-content; color: white;">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn-success">Save</button>
    </form>
    </div>
    <div class="row" style="margin-left: 0%;">
        <div class="col">
          <h3 style="margin-top: 2%;">Aktivitas</h3>
          {% if Ada  %}
          {% for items in list_ak %}
          <div class="card" style="width: 90%;">
            <div class="card-body">
              <h4 class="card-title" style="color: black;">{{ items.aktivitas }}</h4>
              <p class="card-text">
                <p>Peserta: </p>
                  {% for pes in list_pes %}
                    {% if pes.kegiatan == items %}
                    <ul>
                      <li>{{ pes.peserta }}</li>
                    </ul>
                    {% endif %}
                  {% endfor %}
                  </p>
              <div class="d-flex flex-row">
                <a style="margin-left: 20px;" href="{% url 'kegiatan:tambah_peserta' items.id %}" class="card-link btn btn-outline-primary">Tambah Peserta</a>
              </div>
            </div>
          </div>
          {% endfor %}
          {% endif %}
        </div>
      </div>  
</div>
{% endblock content %}

kegiatan/templates/kegiatan/tambah_peserta.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Tambah Peserta</title>
<link rel="stylesheet" href="{% static 'home/style3.css' %}">
{% endblock meta %}
{% block content %}
<div style="margin-top: 30px; margin-left: 27%;" class="peserta-container">
    <div style="margin-top: 20px;">
        <div class="col">
            <h4 style="color: white;">Tambahkan Peserta?</h4>
            <form action="" method="POST" style="display: flex;flex-direction: column; width: fit-content; color: white;">
                {% csrf_token %}
                {{ form }}
                <br>
                <input class="btn btn-primary" type="submit" value="Submit">
            </form>
        </div>
    </div>
    <br>
</div>
{% endblock content %}